### ISSUE TITLE
手动编译安装

### ISSUE THREAD

**Issue by bash-horatio** [xuzhuoyi/LDE#3]
如题，请问怎么手动编译呢？
我用的是Debian的最新版testing/stretch 
直接安装deb包依赖不满足，找不到rqaorqt相关的包

d8089:~$ sudo gdebi --n lde_2.0.1_mipsel.deb 
[sudo] password for light: 
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: razorqt-panel

d8089:~$ sudo apt search rqzorqt
Sorting... Done
Full Text Search... Done

**Comment by xuzhuoyi** [comment]
应该是你输错了包名。这个包在 Debian Stable/Unstable 源里都是有的。
用 sudo apt-get install razorqt-panel 试试。

**Comment by bash-horatio** [comment]
**确实没有** ：-（

```
T520:~$ sudo apt-get install razorqt-panel
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package razorqt-panel
```

`sudo gdebi --n lde_2.0.1_mipsel.deb`
本身就会解析依赖，自动安装依赖包

我用的是testing，源列表为：

```
deb http://debian.ustc.edu.cn/debian/ testing main contrib non-free
#deb-src http://debian.ustc.edu.cn/debian/ testing main contrib

deb http://debian.ustc.edu.cn/debian-security/ testing/updates main contrib non-free
#deb-src http://debian.ustc.edu.cn/debian-security/ testing/updates main contrib

```

**Comment by bash-horatio** [comment]
只有**jessie和sid**有这个包，看来我只能手动编译并打**testing/stretch**的deb包了

```
Exact hits
Package razorqt
    jessie (stable) (metapackages): Lightweight desktop environment, all components
    0.5.2-4: all
    sid (unstable) (metapackages): Lightweight desktop environment, all components
    0.5.2-4: all
```

> https://packages.debian.org/search?keywords=razorqt

**Comment by xuzhuoyi** [comment]
我去查了一下，确实没有。这个包也已经被一些发行版废弃了，最近我准备再更新一次LDE，增加一些功能，更换老旧的依赖。你可以过几天编译新版。

**Comment by bash-horatio** [comment]
好的，谢谢！其实我本来是问，怎么**手动编译**的。我只做过**半年的C开发**，目前只懂**scala和C**，**没有文档**时，不懂编译别人的项目。如果您方便，可以在README里提供compile和install的部分么？再次谢谢你的努力和贡献！

**Comment by xuzhuoyi** [comment]
那个依赖包是运行依赖，手动编译没有那个包也可以，只不过最后底部面板可能无法显示，你可以自己在安装一个别的面板软件代替。
编译说明本来就有，可以看链接 [Debian 类操作系统编译安装说明](https://github.com/xuzhuoyi/LDE/wiki/Debian-%E7%B1%BB%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E)

**Comment by bash-horatio** [comment]
好的，之前没找到这个文档，谢谢！
我明天尝试编译一下，之后再反馈到这里：-）

**Comment by bash-horatio** [comment]
在debian 9（testing/stretch）上，razorqt-panel包，应该是编译依赖，错误如下：

```
T520:~/Gits/LDE/src$ make -j5
cd ldeinit/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/light/Gits/LDE/src/ldeinit/ldeinit.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/light/Gits/LDE/src/ldeinit'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/light/Gits/LDE/src/ldeinit'
cd ldeabout/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/light/Gits/LDE/src/ldeabout/ldeabout.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/light/Gits/LDE/src/ldeabout'
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o main.cpp
g++ -m64 -Wl,-O1 -o ../../usr/bin/ldeabout main.o widget.o laboutwidget.o moc_widget.o moc_laboutwidget.o   -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
main.o: In function `main':
main.cpp:(.text.startup+0x11a): undefined reference to `Widget::Widget(QWidget*)'
main.cpp:(.text.startup+0x1a1): undefined reference to `LAboutWidget::LAboutWidget(QString, QString, QString, QWidget*)'
main.cpp:(.text.startup+0x1d7): undefined reference to `Widget::~Widget()'
main.cpp:(.text.startup+0x237): undefined reference to `Widget::~Widget()'
collect2: error: ld returned 1 exit status
Makefile:154: recipe for target '../../usr/bin/ldeabout' failed
make[1]: *** [../../usr/bin/ldeabout] Error 1
make[1]: Leaving directory '/home/light/Gits/LDE/src/ldeabout'
Makefile:94: recipe for target 'sub-ldeabout-make_first-ordered' failed
make: *** [sub-ldeabout-make_first-ordered] Error 2
```

在usr/bin中只生成了一个`ldeinit`可执行文件：-（

**Comment by xuzhuoyi** [comment]
再安装一个依赖包 `libqt5widgets5` 就行
`sudo apt-get install libqt5widgets5`
我文档里好像漏写了，以前的 Debian 8 好像已经默认安装了这个包

**Comment by xuzhuoyi** [comment]
我刚刚在一个全新安装的 Debian 上按照你的方法编译可以通过，无法重现你的错误。
不过看错误提示好象是编译 widget.c 和 laboutwidget.c 出了问题，你把源代码全部删了，重新用 git 下载到另一目录再编译试试。

**Comment by bash-horatio** [comment]
重新git clone下来，编译成功。
经过检查，不是代码的问题。
由于**debian testing不太稳定**，上午编译失败过一次，中途**g++内存泄漏**，整个电脑卡死。
在物理重起后和编译前，没有用`make clean`清理各个文件夹的**.o对象文件**，所以产生了这个错误。

另外，似乎不一定需要Qt 5和QMake 3+。我通过设置环境变量`QT_SELECT`，发现Qt 4和5
都能成功编译。

**Comment by xuzhuoyi** [comment]
修改 QT_SELECT 应该并没有什么作用。Qt 4 连 widgets 模块都没有，我那些代码都是基于 Qt Widgets 的，你实际上还是使用 Qt 5 在编译。

感谢您的反馈，请继续关注 LDE 的后续版本并提出建议。
