### ISSUE TITLE
ftp://ftp.loongsoner.com/LDE is not available anymore 

### ISSUE THREAD

**Issue by lhsfcboy** [xuzhuoyi/LDE#4]
ftp://ftp.loongsoner.com/LDE is not available anymore

**Comment by xuzhuoyi** [comment]
This site was not maintained by me, and it was closed by maintainers. But you can download in Github release page. [https://github.com/xuzhuoyi/LDE/releases](https://github.com/xuzhuoyi/LDE/releases)
